# Generated by Django 4.2.7 on 2023-12-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_on',
            new_name='booked_on',
        ),
    ]
