# Generated by Django 4.2.7 on 2023-12-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
